### ISSUE TITLE
Plugins not compatible with Totara 11

### ISSUE THREAD

**Issue by logan-reynolds** [beast2013/moodle2-skillsoft-activity#1]
Installing both skillsoft and skillsoftmi plugins on Totara 11.9 build 20181204.00 causes an error that completely crashes page rendering post-install on the /admin/upgradesettings.php page, which results in a blank white screen with no errors logged in browser, php or apache logs.  The same also happens to at least the /admin/plugins.php page (and possibly others), as well as a modal popping up with "Unknown error" when you try to expand the Site Administration navigation menu.  Not sure if Totara is an officially supported platform, but we have a client interested in running this in a Totara 11+ environment.  I'm submitting this issue to determine whether these problems have been encountered before, or may be due to missing libraries or some other configuration setting.

**Comment by beast2013** [comment]
I found an issue with skillsoftmi plugin that was throwing an error. I have fixed that issue. Since I do not have access to Totara can you try installing that plug in again and see if you still encounter that problem.

**Comment by ghost** [comment]
Hello,
I am still seeing "Fatal error: Cannot unset $this in /mnt/code/www/moodle_prod/mod/skillsoftmi/aicclib.php on line 51"   However I do see that I pulled the MOODLE_32_STABLE branch since Totara 12 is based on Moodle 3.2; would it be safe to pull the master branch of both skillsoft and skillsoftmi for all Moodle 3.2+ ?

**Comment by beast2013** [comment]
Hello,
I have changed the code in the MOODLE_32_STABLE branch of the skillsoftmi code and checked that branch in the skillsoft code too. Try pulling both those branches again.

**Comment by ghost** [comment]
Hello,

This resolves the issue; thank you.
